name: gamo_dart
description: An absolute bare-bones web app.
# version: 0.0.1
#homepage: https://www.example.com
#author: CoenB95 <boelhouwers.coen@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  vector_math: ^2.0.8

dev_dependencies:
  build_runner: '>=1.3.0 < 2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
  pedantic: ^1.0.0
